---
apiVersion: v1
kind: Secret
metadata:
  name: mojomayhem-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-atl/mojomayhem-gateway-gitops
